name: 'Build Docker Image & Update Application Helm Chart Values'
on:
  push:
    branches:
      - fleet
env:
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
  DOCKER_PW: ${{ secrets.DOCKER_PW }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
jobs:
  build_image:
    name: Build Image & Update Helm Chart Values
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    steps:
      # Install Node.js dependencies
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      # Login to Docker registry
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
      # Install yq
      - name: Install yq 
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.12.0/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
          yq --version
      # Build and test application
      - name: Build, test and push to Docker Hub
        run: |
          echo Build started on `date`
          echo Run node.js tests...
          npm run test
          CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
          echo Building the Docker image...
          docker build -t lukondefmwila/ecommerce-orders:$CONTAINER_IMAGE_TAG . 
          echo Pushing the Docker image...
          docker push lukondefmwila/ecommerce-orders:$CONTAINER_IMAGE_TAG
      # Clone git repository with Helm charts, update and push changes
      - name: Update image tag in Helm git repo 
        run: | 
          CONTAINER_IMAGE_TAG="$(node -e "console.log(require('./package.json').version);")"
          echo New container image tag: $CONTAINER_IMAGE_TAG
          echo Create temporary folder to clone the repo into...
          TEMP_FOLDER="$(mktemp -d)" 
          echo Clone the repository...
          git clone -b fleet "https://LukeMwila:${ACCESS_TOKEN}@github.com/LukeMwila/microservice-example-helm-charts.git" ${TEMP_FOLDER} 
          cd ${TEMP_FOLDER}/application-charts/orders 
          ls
          echo Update Helm chart values-dev with new image tag
          CONTAINER_IMAGE_TAG=$CONTAINER_IMAGE_TAG yq e -i '.deployment.imageTag = env(CONTAINER_IMAGE_TAG)' ./values.yaml
          echo 'Container image tag updated in orders/values-dev.yaml' 
          cd ../../
          git config user.email "lukemwila.tech@gmail.com" 
          git config user.name "LukeMwila" 
          git add .  
          git commit -m "refactor - updated Helm chart values for dev environment with container image - $CONTAINER_IMAGE_TAG" 
          git push -u origin fleet